fun main() {
    throw Exception("Hello, I'm exception")
}